"""Admin Student face enrollment, privacy, live camera, and fallback controls."""
from dataclasses import dataclass,field
from collections.abc import Callable
import flet as ft
from app.components.ui import empty_state,page_header,section_header,status_badge,surface_card
from app.core.theme import ThemeTokens
from app.core.events import event_handler
@dataclass
class FaceEnrollmentState:
    items:list[dict]=field(default_factory=list);search:str="";status:str="all";loading:bool=False;error:str|None=None
def build_face_enrollment_page(state:FaceEnrollmentState,tokens:ThemeTokens,on_search,on_filter,on_open)->ft.Control:
    rows=[]
    for item in state.items:
        face=item.get("face") or {};enrolled=bool(face.get("enrolled"));rows.append(surface_card(ft.Row([ft.Column([ft.Text(item.get("display_name","Student"),weight=ft.FontWeight.BOLD),ft.Text(item.get("admission_number","—"),size=11,color=tokens["text_secondary"])],expand=True),status_badge("Enrolled" if enrolled else "Not Enrolled",tokens,"success" if enrolled else "warning"),ft.FilledButton("Replace" if enrolled else "Enroll",icon=ft.Icons.FACE_RETOUCHING_NATURAL,on_click=lambda _,record=item:on_open(record))]),tokens))
    body=ft.ProgressRing() if state.loading else empty_state("Face enrollment unavailable",state.error,ft.Icons.ERROR_OUTLINE,tokens) if state.error else ft.Column(rows,spacing=8) if rows else empty_state("No Students found","Adjust the Student search or enrollment filter.",ft.Icons.PERSON_SEARCH,tokens)
    return ft.Container(ft.Column([page_header("Student Face Enrollment","Securely manage institution-scoped biometric templates.",tokens),surface_card(ft.Column([section_header("Privacy Notice",tokens),ft.Text("Approved enrollment frames are private development biometric data. Preview/rejected frames are not retained. Production use requires an explicit consent, retention, deletion, and legal review policy.",color=tokens["text_secondary"])],spacing=8),tokens),ft.ResponsiveRow([ft.TextField(label="Search Student",value=state.search,on_submit=lambda e:on_search(e.control.value),prefix_icon=ft.Icons.SEARCH,col={"xs":12,"md":7}),ft.Dropdown(label="Enrollment",value=state.status,options=[ft.DropdownOption(key=x,text=x.replace("_"," ").title()) for x in ("all","enrolled","not_enrolled")],on_select=lambda e:on_filter(e.control.value),col={"xs":12,"md":5})]),body],spacing=16,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key="admin-face-enrollment")
def build_face_enrollment_dialog(student:dict,tokens:ThemeTokens,on_files:Callable,on_profile:Callable,on_remove:Callable,on_close:Callable,camera_panel:ft.Control|None=None,on_consent:Callable|None=None)->ft.Control:
    face=student.get("face") or {};enrolled=bool(face.get("enrolled"));consent=ft.Checkbox(label="I confirm the Institution has obtained appropriate consent for this biometric enrollment.",value=False,on_change=(lambda e:on_consent(bool(e.control.value))) if on_consent else None)
    def guarded(callback,action):return event_handler(callback,action=action,before=lambda:bool(consent.value))
    before=surface_card(ft.Column([section_header("Before enrollment",tokens),ft.Text("Purpose: create a biometric template for attendance identity checks."),ft.Text("Raw preview and rejected frames are not permanently retained; only three approved enrollment frames are kept locally in private development storage."),ft.Text("Flet has no built-in native camera control; Windows desktop capture remains inside Flet through OpenCV."),ft.Text("Blink challenge-response is development-grade liveness and is not production-grade presentation-attack detection."),consent],spacing=8),tokens)
    fallback=surface_card(ft.Column([section_header("Fallback capture",tokens),ft.Text("If the Windows webcam is unavailable, select three distinct device-captured images. This fallback does not count as a live-camera test.",color=tokens["text_secondary"]),ft.OutlinedButton("Select 3 camera frames",icon=ft.Icons.ADD_A_PHOTO_OUTLINED,on_click=guarded(on_files,"select 3 frames clicked")),ft.OutlinedButton("Use managed profile photo",icon=ft.Icons.PERSON_OUTLINED,on_click=guarded(on_profile,"profile enrollment clicked"))],spacing=9),tokens)
    reference=face.get("referenceImage")
    current=surface_card(ft.Column([section_header("Current template",tokens),*([ft.Image(src=reference,width=160,height=120,fit=ft.BoxFit.COVER,border_radius=12,semantics_label="Authorized enrollment reference")] if reference else []),status_badge(face.get("status","active").title(),tokens,"success"),ft.Text(f"Method: {face.get('method','—')} · Captures: {face.get('captureCount',0)} · Retained images: {face.get('localImageCount',0)}"),ft.Text(f"Development liveness: {'Passed' if face.get('livenessPassed') else 'Not verified'}"),ft.Text(f"Model: {face.get('modelVersion','—')}",size=11,color=tokens["text_secondary"]),ft.OutlinedButton("Remove Template",icon=ft.Icons.DELETE_OUTLINE,on_click=on_remove)],spacing=8),tokens) if enrolled else None
    controls=[page_header(f"Face Enrollment · {student.get('display_name','Student')}","Consent, live capture quality, encryption, and template controls.",tokens),before,*([camera_panel] if camera_panel else []),fallback,*([current] if current else []),ft.Row([ft.TextButton("Close",on_click=on_close)],alignment=ft.MainAxisAlignment.END)]
    return ft.Container(ft.Column(controls,spacing=12,scroll=ft.ScrollMode.AUTO),width=820,height=760,padding=8,key="face-enrollment-dialog")
