"""Production Admin Faculty management workspace."""
from dataclasses import dataclass,field
from typing import Callable
import flet as ft
from app.components.ui import empty_state,metric_card,page_header,status_badge,surface_card
from app.core.theme import ThemeTokens

@dataclass
class FacultyPageState:
    items:list[dict]=field(default_factory=list); loading:bool=False; error:str|None=None; search:str=""; status:str|None=None; department_id:str|None=None; department_options:list[dict]=field(default_factory=list); total:int=0; active_total:int=0; inactive_total:int=0

def build_faculty_page(state:FacultyPageState,tokens:ThemeTokens,on_search:Callable,on_filter:Callable,on_department:Callable,on_refresh:Callable,on_add:Callable,on_import:Callable,on_action:Callable)->ft.Control:
    rows=[]
    for item in state.items:
        rows.append(surface_card(ft.Row([ft.Column([ft.Text(item.get("display_name","Faculty"),weight=ft.FontWeight.BOLD),ft.Text(f"{item.get('employee_id','—')} · {item.get('email','—')}",size=12,color=tokens["text_secondary"])],expand=True),ft.Text(item.get("designation") or "—"),status_badge(str(item.get("status","inactive")).title(),tokens,"success" if item.get("status")=="active" else "warning"),ft.PopupMenuButton(icon=ft.Icons.MORE_VERT,items=[ft.PopupMenuItem(label,icon=icon,on_click=lambda _,fid=item.get("_id"),action=action:on_action(fid,action)) for label,icon,action in (("View",ft.Icons.VISIBILITY_OUTLINED,"view"),("Edit",ft.Icons.EDIT_OUTLINED,"edit"),("Teaching assignments",ft.Icons.CLASS_OUTLINED,"assignments"),("Assign subject",ft.Icons.ADD_TASK,"assign"),(("Deactivate" if item.get("status")=="active" else "Activate"),ft.Icons.POWER_SETTINGS_NEW,"status"))])]),tokens))
    body=ft.ProgressRing() if state.loading else empty_state("Faculty unavailable",state.error,ft.Icons.ERROR_OUTLINE,tokens) if state.error else empty_state("No Faculty found","Add Faculty or adjust filters.",ft.Icons.SCHOOL_OUTLINED,tokens) if not rows else ft.Column(rows,spacing=8)
    department_filter=ft.Dropdown(label="Department",value=state.department_id or "all",options=[ft.DropdownOption(key="all",text="All Departments"),*[ft.DropdownOption(key=str(x.get("_id")),text=f"{x.get('code','')} · {x.get('name','Department')}") for x in state.department_options]],on_select=lambda e:on_department(None if e.control.value=="all" else e.control.value),col={"xs":12,"md":2})
    return ft.Container(ft.Column([page_header("Faculty","Manage Faculty identities, accounts, Departments, and teaching ownership.",tokens),ft.ResponsiveRow([metric_card("Total Faculty",str(state.total),ft.Icons.SCHOOL_OUTLINED,"Institution",tokens,col={"xs":12,"sm":4}),metric_card("Active Faculty",str(state.active_total),ft.Icons.CHECK_CIRCLE_OUTLINED,"Can authenticate",tokens,tone="success",col={"xs":12,"sm":4}),metric_card("Inactive Faculty",str(state.inactive_total),ft.Icons.PAUSE_CIRCLE_OUTLINE,"Access disabled",tokens,tone="warning",col={"xs":12,"sm":4})]),ft.ResponsiveRow([ft.TextField(label="Search name, employee ID, or email",value=state.search,on_submit=lambda e:on_search(e.control.value),col={"xs":12,"md":4}),ft.Dropdown(label="Status",value=state.status or "all",options=[ft.DropdownOption(key="all",text="All"),*[ft.DropdownOption(key=x,text=x.title()) for x in ("active","inactive","suspended","resigned","archived")]],on_select=lambda e:on_filter(None if e.control.value=="all" else e.control.value),col={"xs":12,"md":2}),department_filter,ft.FilledButton("Add Faculty",icon=ft.Icons.PERSON_ADD,on_click=on_add,col={"xs":12,"md":2}),ft.OutlinedButton("Import CSV",icon=ft.Icons.UPLOAD_FILE,on_click=on_import,col={"xs":12,"md":2}),ft.IconButton(ft.Icons.REFRESH,on_click=on_refresh)]),body],spacing=16,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key="admin-faculty-page")

def build_faculty_form(tokens,on_submit,on_cancel,record=None,departments=None):
    record=record or {}; create=not record
    specs=[("display_name","Full name"),("employee_id","Employee ID"),("email","Email"),("username","Username"),("temporary_password","Temporary password"),("phone","Phone"),("department_id","Department ID"),("designation","Designation"),("joining_date","Joining date (YYYY-MM-DD)")]
    fields={n:ft.TextField(label=l,value=str(record.get(n) or ""),password=n=="temporary_password",can_reveal_password=n=="temporary_password",visible=create or n not in {"employee_id","username","temporary_password"}) for n,l in specs}
    if departments: fields["department_id"]=ft.Dropdown(label="Department",value=str(record.get("department_id") or "") or None,options=[ft.DropdownOption(key=str(x.get("_id")),text=f"{x.get('code','')} · {x.get('name','Department')}") for x in departments],enable_search=True)
    return ft.Container(ft.Column([page_header("Add Faculty" if create else "Edit Faculty","Account credentials remain separate from the Faculty profile.",tokens),ft.ResponsiveRow([ft.Container(x,col={"xs":12,"md":6}) for x in fields.values()]),ft.Row([ft.TextButton("Cancel",on_click=on_cancel),ft.FilledButton("Save Faculty",on_click=lambda _:on_submit({k:v.value for k,v in fields.items() if v.visible and v.value}))],alignment=ft.MainAxisAlignment.END)],spacing=12,scroll=ft.ScrollMode.AUTO),width=720,height=620,padding=8)

def build_assignment_form(tokens,on_submit,on_cancel,options=None):
    options=options or {}; years=options.get("years",[]); classes=options.get("classes",[]); subjects=options.get("subjects",[])
    year=ft.Dropdown(label="Academic Year",options=[ft.DropdownOption(key=str(x.get("_id")),text=x.get("name","Academic Year")) for x in years]); division=ft.Dropdown(label="Class / Division",disabled=True); subject=ft.Dropdown(label="Subject",disabled=True)
    def year_changed(_):
        division.options=[ft.DropdownOption(key=str(x.get("_id")),text=f"{x.get('name','Class')} · {x.get('division','')}") for x in classes if str(x.get("academic_year_id"))==str(year.value)];division.value=None;division.disabled=False;subject.value=None;subject.options=[];subject.disabled=True;division.update();subject.update()
    def class_changed(_):
        selected=next((x for x in classes if str(x.get("_id"))==str(division.value)),{});subject.options=[ft.DropdownOption(key=str(x.get("_id")),text=f"{x.get('code','')} · {x.get('name','Subject')}") for x in subjects if str(x.get("program_id"))==str(selected.get("program_id")) and str(x.get("semester_id"))==str(selected.get("semester_id"))];subject.value=None;subject.disabled=False;subject.update()
    year.on_select=year_changed;division.on_select=class_changed
    start=ft.TextField(label="Start date (optional)");end=ft.TextField(label="End date (optional)");kind=ft.Dropdown(label="Assignment type",value="primary",options=[ft.DropdownOption(key=x,text=x.replace("_"," ").title()) for x in ("primary","co_faculty","practical","project_guide")])
    return ft.Container(ft.Column([page_header("Assign Subject","Academic Year → Class → Subject selection is hierarchy-aware.",tokens),year,division,subject,start,end,kind,ft.Text("Only Subjects matching the selected Class Program and Semester are offered and accepted.",size=11,color=tokens["text_secondary"]),ft.Row([ft.TextButton("Cancel",on_click=on_cancel),ft.FilledButton("Confirm Assignment",on_click=lambda _:on_submit({k:v for k,v in {"academic_year_id":year.value,"class_division_id":division.value,"subject_id":subject.value,"start_date":start.value,"end_date":end.value,"assignment_type":kind.value}.items() if v}))],alignment=ft.MainAxisAlignment.END)],spacing=10,scroll=ft.ScrollMode.AUTO),width=620,height=590,padding=8)

def build_faculty_details(record,tokens,on_close):
    account=record.get("account") or {}; assignments=record.get("assignments") or []
    assignment_rows=[ft.Text(f"{x.get('assignment_type','—').replace('_',' ').title()} · {(x.get('subject') or {}).get('name',x.get('subject_id','—'))} · {(x.get('class_division') or {}).get('name',x.get('class_division_id','—'))} · {x.get('status','—')}",size=12) for x in assignments]
    return ft.Container(ft.Column([page_header(record.get("display_name","Faculty"),"Profile, account state, and teaching ownership.",tokens),surface_card(ft.Column([ft.Text(f"Employee ID: {record.get('employee_id','—')}"),ft.Text(f"Email: {record.get('email','—')}"),ft.Text(f"Designation: {record.get('designation','—')}"),ft.Text(f"Department: {(record.get('department') or {}).get('name',record.get('department_id','—'))}"),ft.Text(f"Account: {account.get('status','—')}")],spacing=8),tokens),surface_card(ft.Column([ft.Text("Teaching Assignments",weight=ft.FontWeight.BOLD),*(assignment_rows or [ft.Text("No active teaching assignments.")])],spacing=8),tokens),empty_state("Schedule unavailable","Schedule becomes available after timetable setup.",ft.Icons.CALENDAR_MONTH_OUTLINED,tokens),ft.Row([ft.FilledButton("Close",on_click=on_close)],alignment=ft.MainAxisAlignment.END)],spacing=12,scroll=ft.ScrollMode.AUTO),width=720,height=650,padding=8)
