"""Responsive manual and live face attendance workflow for Faculty."""
from collections.abc import Callable
import flet as ft
from app.components.ui import empty_state,page_header,section_header,status_badge,surface_card
from app.core.theme import ThemeTokens

def build_take_attendance(tokens:ThemeTokens,schedule:dict|None,sessions:list[dict]|None,current:dict|None,on_start:Callable[[dict],None],on_open:Callable[[str],None],on_mark:Callable[[str,str],None],on_save:Callable,on_submit:Callable,notice:str|None=None,search:str="",status_filter:str="all",on_filter:Callable|None=None,mode:str="manual",face_status:dict|None=None,face_result:dict|None=None,on_mode:Callable|None=None,on_face_capture:Callable|None=None,recognition_mode:str="all",selected_student_id:str|None=None,on_recognition_mode:Callable|None=None,on_selected_student:Callable|None=None,camera_panel:ft.Control|None=None,reference_image:bytes|None=None)->ft.Control:
    if current:
        all_records=current.get("records") or [];summary=current.get("summary") or {};editable=current.get("status") in {"draft","reopened"};records=[x for x in all_records if (not search or search.casefold() in f"{x.get('student_name','')} {x.get('roll_number','')}".casefold()) and (status_filter=="all" or (x.get("status") or "unmarked")==status_filter)]
        roster=[]
        for record in records:
            buttons=[(ft.FilledButton if record.get("status")==value else ft.OutlinedButton)(value.title(),on_click=lambda _,sid=record["student_id"],state=value:on_mark(sid,state),disabled=not editable) for value in ("present","absent","late","excused")]
            roster.append(surface_card(ft.ResponsiveRow([ft.Container(ft.Column([ft.Text(record.get("student_name","Student"),weight=ft.FontWeight.BOLD),ft.Text(f"Roll {record.get('roll_number') or '-'}",size=11,color=tokens["text_secondary"])],spacing=2),col={"xs":12,"md":4}),ft.Container(ft.Row(buttons,wrap=True,spacing=5),col={"xs":12,"md":8})],vertical_alignment=ft.CrossAxisAlignment.CENTER),tokens,key=f"attendance-student-{record['student_id']}"))
        filters=ft.ResponsiveRow([ft.TextField(label="Search Student or roll number",value=search,prefix_icon=ft.Icons.SEARCH,on_change=(lambda e:on_filter(search=e.control.value)) if on_filter else None,col={"xs":12,"md":7}),ft.Dropdown(label="Status",value=status_filter,options=[ft.DropdownOption(key=x,text=x.title()) for x in ("all","unmarked","present","absent","late","excused")],on_select=(lambda e:on_filter(status=e.control.value)) if on_filter else None,col={"xs":12,"md":5})])
        tabs=ft.SegmentedButton(selected={mode},segments=[ft.Segment(value="manual",label=ft.Text("Manual Attendance"),icon=ft.Icon(ft.Icons.FACT_CHECK_OUTLINED)),ft.Segment(value="face",label=ft.Text("Face Attendance"),icon=ft.Icon(ft.Icons.FACE_RETOUCHING_NATURAL))],on_change=(lambda e:on_mode(next(iter(e.control.selected)))) if on_mode else None)
        stats=(face_status or {}).get("stats",{});cap=(face_status or {}).get("capability",{});result=(face_result or {}).get("result")
        mode_controls=ft.ResponsiveRow([ft.Dropdown(label="Recognition mode",value=recognition_mode,options=[ft.DropdownOption(key="all",text="Identify anyone in roster"),ft.DropdownOption(key="specific",text="Verify selected student")],on_select=(lambda e:on_recognition_mode(e.control.value)) if on_recognition_mode else None,col={"xs":12,"md":5}),ft.Dropdown(label="Student to verify",value=selected_student_id,disabled=recognition_mode!="specific",options=[ft.DropdownOption(key=str(x["student_id"]),text=f"{x.get('student_name','Student')} - {x.get('roll_number') or 'No roll'}") for x in all_records],on_select=(lambda e:on_selected_student(e.control.value)) if on_selected_student else None,col={"xs":12,"md":7})])
        fallback=ft.OutlinedButton("Select a recent frame",icon=ft.Icons.IMAGE_SEARCH,on_click=on_face_capture,disabled=not editable or cap.get("faceAttendance")!="available" or (recognition_mode=="specific" and not selected_student_id))
        message={"identified":"Student identified - Present suggested and remains editable.","verified":"Selected student verified - Present suggested and remains editable.","not_verified":"The face does not verify the selected student. Nothing was marked.","student_not_enrolled":"Selected student is outside this session roster.","already_recognized":"Already recognized; cooldown prevented a duplicate.","unknown":"Face not recognized. Use Manual Attendance if needed.","ambiguous":"Multiple close matches; nobody was marked.","no_face":"No face detected.","multiple_faces":"Only one face is allowed.","quality_rejected":"Improve lighting, move closer, and hold steady.","liveness_failed":"Development pose challenge was not completed. Nothing was marked.","ai_unavailable":"Face AI unavailable. Continue with Manual Attendance."}.get(result,"Ready for one clear, well-lit face.")
        camera=camera_panel or ft.Container(ft.Column([ft.Icon(ft.Icons.VIDEOCAM_OFF_OUTLINED,size=56,color=tokens["text_secondary"]),ft.Text("Live Windows camera is not active.",color=tokens["text_secondary"])],horizontal_alignment=ft.CrossAxisAlignment.CENTER),padding=20,border=ft.Border.all(1,tokens["border"]),border_radius=16)
        reference=ft.Column([ft.Text("Enrolled Reference",weight=ft.FontWeight.BOLD),ft.Image(src=reference_image,width=150,height=110,fit=ft.BoxFit.COVER,border_radius=12,semantics_label="Authorized roster enrollment reference")],spacing=6) if reference_image else None
        matched=(face_result or {}).get("student") or {};confidence=((face_result or {}).get("confidence") or {}).get("score");result_details=ft.ResponsiveRow([ft.Container(ft.Text(f"Result: {matched.get('displayName','-')}",weight=ft.FontWeight.BOLD),col={"xs":12,"md":4}),ft.Container(ft.Text(f"Admission: {matched.get('admissionNumber') or '-'}"),col={"xs":12,"md":4}),ft.Container(ft.Text(f"Confidence: {confidence if confidence is not None else '-'}"),col={"xs":12,"md":4})]) if result in {"identified","verified","already_recognized"} else None
        face_body=surface_card(ft.Column([section_header("AI-Assisted Face Attendance",tokens,"Choose roster-wide identification or verify one selected Student."),ft.Row([status_badge(f"Roster {stats.get('roster',len(all_records))}",tokens),status_badge(f"Face Enrolled {stats.get('faceEnrolled',0)}",tokens,"primary"),status_badge(f"Recognized {stats.get('recognized',0)}",tokens,"success"),status_badge(f"Remaining {stats.get('remaining',len(all_records))}",tokens,"warning"),status_badge(f"Manual-only {stats.get('manualOnly',0)}",tokens,"secondary")],wrap=True),mode_controls,*([reference] if reference else []),camera,fallback,ft.Text("Blink challenge-response is development-grade liveness. It does not provide production-grade presentation-attack detection.",size=11,color=tokens["text_secondary"]),ft.Text(message,color=tokens["success"] if result in {"identified","verified"} else tokens["text_secondary"]),*([result_details] if result_details else []),ft.Text(f"Detector: {cap.get('detector','unavailable')} | Recognizer: {cap.get('recognizer','unavailable')} | Encryption: {cap.get('encryption','not_configured')}",size=11,color=tokens["text_secondary"])],spacing=14),tokens,key="faculty-face-attendance")
        manual_body=ft.Column([filters,*(roster or [empty_state("No matching Students","Adjust the roster search or status filter.",ft.Icons.GROUP_OFF_OUTLINED,tokens)])],spacing=10)
        return ft.Container(ft.Column([page_header("Take Attendance",f"Session status: {current.get('status','draft').title()}",tokens),tabs,ft.Row([status_badge(f"{summary.get('total',len(all_records))} Students",tokens,"primary"),status_badge(f"{summary.get('present',0)} Present",tokens,"success"),status_badge(f"{summary.get('absent',0)} Absent",tokens,"danger"),status_badge(f"{summary.get('late',0)} Late",tokens,"warning"),status_badge(f"{summary.get('excused',0)} Excused",tokens,"secondary")],wrap=True),face_body if mode=="face" else manual_body,ft.Row([ft.OutlinedButton("Save Draft",icon=ft.Icons.SAVE_OUTLINED,on_click=on_save,disabled=not editable),ft.FilledButton("Review & Submit",icon=ft.Icons.CHECK_CIRCLE_OUTLINE,on_click=on_submit,disabled=not editable or summary.get("unmarked",1)>0)],wrap=True),*([ft.Text(notice,color=tokens["danger"])] if notice else [])],spacing=14,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key="faculty-attendance-session")
    today=(schedule or {}).get("today") or [];drafts=[x for x in (sessions or []) if x.get("status") in {"draft","reopened"}];recent=[x for x in (sessions or []) if x.get("status") in {"submitted","locked"}]
    lecture_cards=[surface_card(ft.Row([ft.Column([ft.Text((x.get("subject") or {}).get("name","Subject"),weight=ft.FontWeight.BOLD),ft.Text(f"{x.get('startTime')}-{x.get('endTime')} | {x.get('room') or 'Room not set'}",color=tokens["text_secondary"])],expand=True),ft.FilledButton("Start Attendance",icon=ft.Icons.CO_PRESENT_OUTLINED,on_click=lambda _,item=x:on_start(item))]),tokens) for x in today]
    draft_rows=[ft.ListTile(title=ft.Text(f"{x.get('lecture_date','Lecture')} | Draft"),subtitle=ft.Text(f"{x.get('scheduled_start')}-{x.get('scheduled_end')}"),trailing=ft.TextButton("Continue",on_click=lambda _,sid=x["_id"]:on_open(sid))) for x in drafts]
    recent_rows=[ft.ListTile(title=ft.Text(str(x.get("lecture_date","Lecture"))),subtitle=ft.Text(x.get("status","submitted").title()),trailing=status_badge(x.get("status","submitted").title(),tokens,"success")) for x in recent[:8]]
    return ft.Container(ft.Column([page_header("Take Attendance","Start today's lecture or continue an unfinished draft.",tokens),surface_card(ft.Column([section_header("Today's Lectures",tokens),*(lecture_cards or [empty_state("No lectures today","Only your active timetable lectures appear here.",ft.Icons.EVENT_AVAILABLE,tokens)])],spacing=10),tokens),surface_card(ft.Column([section_header("Continue Previous Attendance",tokens),*(draft_rows or [ft.Text("No unfinished drafts.",color=tokens["text_secondary"])])],spacing=6),tokens),surface_card(ft.Column([section_header("Recent Sessions",tokens),*(recent_rows or [ft.Text("No submitted sessions yet.",color=tokens["text_secondary"])])],spacing=6),tokens),*([ft.Text(notice,color=tokens["danger"])] if notice else [])],spacing=16,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key="faculty-take-attendance")
