"""Interactive responsive reports UI for Admin, Faculty, and Student."""
from collections.abc import Callable
import flet as ft
from app.components.ui import empty_state,metric_card,page_header,section_header,status_badge,surface_card
from app.core.theme import ThemeTokens

def _pct(value):return "—" if value is None else f"{float(value):.1f}%"
def _opts(items):return [ft.DropdownOption(key="",text="All")]+[ft.DropdownOption(key=str(x["id"]),text=str(x["label"])) for x in items]
def _source(data,name):
    row=next((x for x in data.get("sourceDistribution",[]) if x.get("source")==name),None);return _pct(row.get("percentage")) if row else "—"

def build_student_detail(data,tokens,on_close):
    stats=data.get("attendance",{});rows=[ft.DataRow(cells=[ft.DataCell(ft.Text(str(x.get(k,"—")) if k!="percentage" else _pct(x.get(k)))) for k in ("subject","classesHeld","present","late","absent","percentage")]) for x in data.get("subjects",[])]
    history=[ft.ListTile(title=ft.Text(x.get("subject","Subject")),subtitle=ft.Text(str(x.get("date",""))),trailing=status_badge(str(x.get("status","—")).title(),tokens)) for x in data.get("recentHistory",[])]
    return ft.Container(ft.Column([page_header(data.get("student","Student"),f"Student ID: {data.get('studentNumber') or data.get('studentId','—')}",tokens),ft.Text(f"Overall attendance: {_pct(stats.get('percentage'))}",size=20,weight=ft.FontWeight.BOLD),ft.Row([ft.DataTable(columns=[ft.DataColumn(label=ft.Text(x)) for x in ("Subject","Held","Present","Late","Absent","Attendance")],rows=rows)],scroll=ft.ScrollMode.AUTO),section_header("Recent Finalized Attendance",tokens),*(history or [ft.Text("No recent finalized attendance.")]),ft.FilledButton("Close",on_click=on_close)],spacing=12,scroll=ft.ScrollMode.AUTO),width=760,height=620,padding=8,key="report-student-detail")

def build_session_detail(data,tokens,on_close,on_export):
    stats=data.get("attendance",{});rows=[ft.DataRow(cells=[ft.DataCell(ft.Text(str(x.get(k) or "—").replace("_"," ").title() if k in {"status","source"} else str(x.get(k) or "—"))) for k in ("student","studentNumber","status","source")]) for x in data.get("students",[])]
    return ft.Container(ft.Column([page_header(data.get("subject","Session Report"),f"{data.get('date','')} · {data.get('class','Class')} · {data.get('faculty','Faculty')}",tokens),ft.Row([status_badge(f"Roster {data.get('totalRoster',0)}",tokens),status_badge(f"Present {stats.get('present',0)}",tokens,"success"),status_badge(f"Late {stats.get('late',0)}",tokens,"warning"),status_badge(f"Absent {stats.get('absent',0)}",tokens,"danger"),status_badge(_pct(stats.get("percentage")),tokens)],wrap=True),ft.Row([ft.DataTable(columns=[ft.DataColumn(label=ft.Text(x)) for x in ("Student","ID","Status","Source")],rows=rows)],scroll=ft.ScrollMode.AUTO),ft.Row([ft.OutlinedButton("Export CSV",icon=ft.Icons.DOWNLOAD_OUTLINED,on_click=lambda _:on_export("sessions",data.get("sessionId"))),ft.FilledButton("Close",on_click=on_close)])],spacing=12,scroll=ft.ScrollMode.AUTO),width=780,height=620,padding=8,key="report-session-detail")

def build_class_detail(data,tokens,on_close,on_student,on_export):
    stats=data.get("attendance",{});rows=[ft.DataRow(cells=[ft.DataCell(ft.Text(str(x.get("student","Student")))),ft.DataCell(ft.Text(str(x.get("studentNumber") or "—"))),ft.DataCell(ft.Text(_pct(x.get("percentage")))),ft.DataCell(ft.Text(str(x.get("present",0)))),ft.DataCell(ft.Text(str(x.get("absent",0)))),ft.DataCell(ft.TextButton("View",on_click=lambda _,sid=x["studentId"]:on_student(sid)))]) for x in data.get("students",[])]
    return ft.Container(ft.Column([page_header("Class Report",f"{data.get('finalizedSessions',0)} finalized sessions",tokens),ft.Row([status_badge(f"Attendance {_pct(stats.get('percentage'))}",tokens),status_badge(f"Students {data.get('totalStudents',0)}",tokens)],wrap=True),ft.Row([ft.DataTable(columns=[ft.DataColumn(label=ft.Text(x)) for x in ("Student","ID","Attendance","Present","Absent","Action")],rows=rows)],scroll=ft.ScrollMode.AUTO),ft.Row([ft.OutlinedButton("Export CSV",icon=ft.Icons.DOWNLOAD_OUTLINED,on_click=lambda _:on_export("classes",data.get("classDivisionId"))),ft.FilledButton("Close",on_click=on_close)])],spacing=12,scroll=ft.ScrollMode.AUTO),width=760,height=600,padding=8,key="report-class-detail")

def build_reports(role:str,tokens:ThemeTokens,data:dict|None,error:str|None=None,on_refresh=None,*,loading=False,options=None,filters=None,low=None,on_filter:Callable|None=None,on_reset=None,on_range=None,on_page=None,on_search=None,on_student=None,on_session=None,on_class=None,on_export=None)->ft.Control:
    data=data or {};options=options or {};filters=filters or {};low=low or {};attendance=data.get("attendance") or {};subjects=data.get("subjects") or [];sources=data.get("sourceDistribution") or []
    if loading:return ft.Container(ft.Column([page_header("Reports & Analytics",f"{role} authorized scope",tokens),surface_card(ft.Row([ft.ProgressRing(),ft.Text("Loading attendance report...")]),tokens,key="reports-loading")],spacing=16),padding=24,expand=True,key=f"{role.casefold()}-reports")
    body=[page_header("Reports & Analytics",f"{role} authorized scope · official finalized attendance only",tokens)]
    if role in {"Admin","Faculty"}:
        programs=[x for x in options.get("programs",[]) if not filters.get("departmentId") or x.get("departmentId")==filters.get("departmentId")];classes=[x for x in options.get("classes",[]) if (not filters.get("programId") or x.get("programId")==filters.get("programId")) and (not filters.get("semesterId") or x.get("semesterId")==filters.get("semesterId"))]
        specs=[("classDivisionId","Assigned Class" if role=="Faculty" else "Division / Class",classes),("subjectId","Assigned Subject" if role=="Faculty" else "Subject",options.get("subjects",[]))] if role=="Faculty" else [("academicYearId","Academic Year",options.get("academicYears",[])),("departmentId","Department",options.get("departments",[])),("programId","Program",programs),("semesterId","Semester",options.get("semesters",[])),("classDivisionId","Division / Class",classes),("subjectId","Subject",options.get("subjects",[]))]
        fields=[ft.Dropdown(label=label,value=filters.get(key) or "",options=_opts(items),on_select=lambda e,k=key:on_filter(k,e.control.value),col={"xs":12,"md":4,"lg":2}) for key,label,items in specs]
        fields += [ft.TextField(label="From YYYY-MM-DD",value=filters.get("dateFrom","") or "",on_submit=lambda e:on_filter("dateFrom",e.control.value),col={"xs":6,"lg":2}),ft.TextField(label="To YYYY-MM-DD",value=filters.get("dateTo","") or "",on_submit=lambda e:on_filter("dateTo",e.control.value),col={"xs":6,"lg":2})]
        body.append(surface_card(ft.Column([section_header("Filters",tokens,"Only authorized finalized-data options are listed."),ft.ResponsiveRow(fields),ft.Row([ft.OutlinedButton("Last 7 days",on_click=lambda _:on_range(7)),ft.OutlinedButton("Last 30 days",on_click=lambda _:on_range(30)),ft.TextButton("Reset Filters",icon=ft.Icons.RESTART_ALT,on_click=on_reset)],wrap=True)],spacing=10),tokens,key="reports-filters"))
    if role=="Student":cards=[metric_card("Overall Attendance",_pct(attendance.get("percentage")),ft.Icons.QUERY_STATS,"Finalized only",tokens,col={"xs":6,"lg":3}),metric_card("Classes Attended",str(attendance.get("present",0)),ft.Icons.CHECK_CIRCLE_OUTLINED,"Present + late",tokens,tone="success",col={"xs":6,"lg":3}),metric_card("Classes Missed",str(attendance.get("absent",0)),ft.Icons.EVENT_BUSY_OUTLINED,"Absent",tokens,tone="danger",col={"xs":6,"lg":3}),metric_card("Eligible Classes",str(attendance.get("eligible",0)),ft.Icons.FACT_CHECK_OUTLINED,"Finalized denominator",tokens,col={"xs":6,"lg":3})]
    else:cards=[metric_card("Overall Attendance",_pct(attendance.get("percentage")),ft.Icons.QUERY_STATS,"Finalized only",tokens,col={"xs":6,"lg":2}),metric_card("Finalized Sessions",str(data.get("finalizedSessions","—")),ft.Icons.FACT_CHECK_OUTLINED,"Submitted + locked",tokens,col={"xs":6,"lg":2}),metric_card("Below Threshold",str(data.get("studentsBelowThreshold","—")),ft.Icons.WARNING_AMBER_OUTLINED,f"Threshold {data.get('threshold',75):g}%",tokens,tone="warning",col={"xs":6,"lg":2}),metric_card("Classes Conducted",str(data.get("classesConducted","—")),ft.Icons.CLASS_OUTLINED,"Official sessions",tokens,col={"xs":6,"lg":2}),metric_card("Manual Attendance",_source(data,"manual"),ft.Icons.EDIT_NOTE,"Finalized records",tokens,col={"xs":6,"lg":2}),metric_card("Face-Assisted",_source(data,"face_assisted"),ft.Icons.FACE_OUTLINED,"Aggregate only",tokens,col={"xs":6,"lg":2})]
    body.append(ft.ResponsiveRow(cards))
    if error:body.append(surface_card(ft.Row([ft.Icon(ft.Icons.ERROR_OUTLINE,color=tokens["danger"]),ft.Text(error or "Unable to load report. Retry.",expand=True),ft.TextButton("Retry",on_click=on_refresh)]),tokens,key="reports-error"))
    if attendance.get("eligible") in (None,0):body.append(empty_state("No finalized attendance data","Official analytics appear after submission.",ft.Icons.QUERY_STATS,tokens))
    subject_rows=[]
    for x in subjects:
        actions=[ft.TextButton("Open Class",on_click=lambda _,cid=x.get("classDivisionId"):on_class(cid))] if x.get("classDivisionId") else []
        if role=="Admin":actions.append(ft.IconButton(ft.Icons.DOWNLOAD_OUTLINED,tooltip="Export subject CSV",on_click=lambda _,sid=x.get("subjectId"):on_export("subjects",sid)))
        subject_rows.append(ft.Container(ft.Row([ft.Column([ft.Text(x.get("subject","Subject"),weight=ft.FontWeight.BOLD),ft.Text(f"{x.get('classesConducted',x.get('classesHeld',0))} classes · {x.get('present',0)} present · {x.get('late',0)} late · {x.get('absent',0)} absent",size=11,color=tokens["text_secondary"])],expand=True),*([status_badge(x["status"],tokens,"success" if x["status"]=="Good" else "warning")] if x.get("status") else []),ft.Text(_pct(x.get("percentage")),weight=ft.FontWeight.BOLD),*actions]),padding=10,border=ft.Border.only(bottom=ft.BorderSide(1,tokens["border"]))))
    body.append(surface_card(ft.Column([section_header("Subject Analytics",tokens),*(subject_rows or [ft.Text("No subject analytics for the selected scope.",color=tokens["text_secondary"])])],spacing=6),tokens,key="reports-subjects"))
    if role=="Admin":
        pagination=low.get("pagination",{});rows=[]
        for x in low.get("items",[]):rows.append(ft.DataRow(cells=[ft.DataCell(ft.Text(str(x.get(k,"—")) if k not in {"percentage","subjectsBelowThreshold"} else _pct(x.get(k)) if k=="percentage" else ", ".join(x.get(k,[])) or "—")) for k in ("student","studentNumber","class","percentage","subjectsBelowThreshold","present","absent","eligible")]+[ft.DataCell(ft.TextButton("View Details",on_click=lambda _,sid=x["studentId"]:on_student(sid)))]))
        table=ft.Row([ft.DataTable(columns=[ft.DataColumn(label=ft.Text(x)) for x in ("Student","Student ID","Class","Overall","Subjects Below","Present","Absent","Eligible","Action")],rows=rows)],scroll=ft.ScrollMode.AUTO) if rows else empty_state("No students below the selected threshold.","Try another scope.",ft.Icons.CHECK_CIRCLE_OUTLINE,tokens)
        body.append(surface_card(ft.Column([ft.Row([section_header("Low Attendance",tokens),ft.OutlinedButton("Export CSV",icon=ft.Icons.DOWNLOAD_OUTLINED,on_click=lambda _:on_export("low-attendance",None))],alignment=ft.MainAxisAlignment.SPACE_BETWEEN),ft.TextField(label="Search Student, ID or Class",value=filters.get("search","") or "",prefix_icon=ft.Icons.SEARCH,on_submit=lambda e:on_search(e.control.value)),table,ft.Row([ft.OutlinedButton("Previous",disabled=pagination.get("page",1)<=1,on_click=lambda _:on_page(pagination.get("page",1)-1)),ft.Text(f"Page {pagination.get('page',1)} of {pagination.get('pages',1)}"),ft.OutlinedButton("Next",disabled=pagination.get("page",1)>=pagination.get("pages",1),on_click=lambda _:on_page(pagination.get("page",1)+1))],alignment=ft.MainAxisAlignment.END)],spacing=10),tokens,key="reports-low-attendance"))
    if sources:body.append(surface_card(ft.Column([section_header("Attendance Source Distribution",tokens),*[ft.Row([ft.Text(str(x.get("source","other")).replace("_"," ").title(),expand=True),ft.ProgressBar(value=(x.get("percentage") or 0)/100,width=180),ft.Text(_pct(x.get("percentage")),width=60)]) for x in sources]],spacing=10),tokens,key="reports-sources"))
    trend=(data.get("trend") or {}).get("items",[]) if role=="Student" else data.get("trend",[])
    if trend:body.append(surface_card(ft.Column([section_header("Attendance Trend",tokens),*[ft.Row([ft.Text(str(x.get("date")),width=100),ft.ProgressBar(value=(x.get("percentage") or 0)/100,expand=True),ft.Text(_pct(x.get("percentage")),width=60)]) for x in trend[-30:]]],spacing=7),tokens,key="reports-trend"))
    sessions=data.get("recentSessions",[])
    if sessions:body.append(surface_card(ft.Column([section_header("Recent Finalized Sessions",tokens),*[ft.ListTile(title=ft.Text(x.get("subject","Subject")),subtitle=ft.Text(f"{x.get('date','')} · {x.get('class','Class')}"),trailing=ft.TextButton("Open",on_click=lambda _,sid=x["sessionId"]:on_session(sid))) for x in sessions]],spacing=4),tokens,key="reports-sessions"))
    history=data.get("recentHistory",[])
    if history:body.append(surface_card(ft.Column([section_header("Recent Attendance",tokens),*[ft.ListTile(title=ft.Text(x.get("subject","Subject")),subtitle=ft.Text(str(x.get("date",""))),trailing=status_badge(str(x.get("status","—")).title(),tokens)) for x in history]],spacing=4),tokens,key="reports-history"))
    return ft.Container(ft.Column(body,spacing=16,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key=f"{role.casefold()}-reports")
