"""Real Student attendance summary and history surface."""
import flet as ft
from app.components.ui import attendance_progress_card,empty_state,metric_card,page_header,section_header,status_badge,surface_card
from app.core.theme import ThemeTokens

def build_student_attendance(tokens:ThemeTokens,data:dict|None,history:list[dict]|None)->ft.Control:
    data=data or {};summary=data.get("summary") or {};subjects=data.get("subjects") or [];percentage=float(summary.get("attendancePercentage",0));rows=[ft.ListTile(title=ft.Text(str(x.get("lectureDate","Lecture"))),subtitle=ft.Text(f"Subject {x.get('subjectId','—')}"),trailing=status_badge(str(x.get("status","unmarked")).title(),tokens,{"present":"success","absent":"danger","late":"warning"}.get(x.get("status"),"secondary"))) for x in (history or [])[:20]]
    metrics=ft.ResponsiveRow([metric_card("Total Classes",str(summary.get("total",0)),ft.Icons.MENU_BOOK_OUTLINED,"Submitted and locked",tokens,col={"xs":6,"lg":3}),metric_card("Present",str(summary.get("present",0)),ft.Icons.CHECK_CIRCLE_OUTLINED,"On time",tokens,tone="success",col={"xs":6,"lg":3}),metric_card("Absent",str(summary.get("absent",0)),ft.Icons.ERROR_OUTLINE,"Counts against percentage",tokens,tone="danger",col={"xs":6,"lg":3}),metric_card("Late / Excused",f"{summary.get('late',0)} / {summary.get('excused',0)}",ft.Icons.SCHEDULE,"Late counts attended",tokens,tone="warning",col={"xs":6,"lg":3})])
    ring=surface_card(ft.Row([ft.ProgressRing(value=percentage/100,width=110,height=110,semantics_label="Overall attendance",semantics_value=percentage),ft.Column([ft.Text(f"{percentage:.1f}%",size=28,weight=ft.FontWeight.BOLD),ft.Text("Present + Late / Present + Late + Absent",color=tokens["text_secondary"]),ft.Text("Excused classes are excluded from the denominator.",size=11,color=tokens["text_secondary"])],expand=True)],vertical_alignment=ft.CrossAxisAlignment.CENTER),tokens)
    subject_cards=[attendance_progress_card(f"Subject {x.get('subjectId','—')}",float(x.get("attendancePercentage",0)),"Safe" if float(x.get("attendancePercentage",0))>=75 else "Watch",tokens) for x in subjects]
    return ft.Container(ft.Column([page_header("My Attendance","Only your own submitted attendance records are shown.",tokens),ring,metrics,surface_card(ft.Column([section_header("Subject Attendance",tokens),*(subject_cards or [empty_state("No subject attendance","Submitted sessions will appear here.",ft.Icons.QUERY_STATS,tokens)])],spacing=10),tokens),surface_card(ft.Column([section_header("Recent Attendance",tokens),*(rows or [empty_state("No attendance history","No submitted records are available.",ft.Icons.HISTORY,tokens)])],spacing=4),tokens)],spacing=16,scroll=ft.ScrollMode.AUTO),padding=24,expand=True,key="student-attendance")
